### ISSUE TITLE
ghc 8.10, 8.0 compat ?

### ISSUE THREAD

**Issue by simonmichael** [serokell/haskell-with-utf8#10]
Thanks for with-utf8!

I've been thinking about using it in a project which supports GHC 8.0 to 8.10, but I don't see a build plan for 8.0 or 8.10 at https://matrix.hackage.haskell.org/#/package/with-utf8 . Is that a minor fix ?

**Comment by kirelagin** [comment]
Ooops, I totally forgot about this, I am sorry. I think it was blocked on dzhus/th-env#1, and then I bumped this dependency here in the repo, but forgot to make a new release.

I’ll make sure everything works and will publish a new release.

**Comment by kirelagin** [comment]
hmm, actually, to be precise, I guess it did not work back then simply because Hackage Matrix did not have a compatible version of `th-env`. I guess, simply forcing it to retry build would work, although I have no idea how to do it.

Anyway, I have released a new version, so let’s wait and see – hopefully, it will be green this time!

**Comment by kirelagin** [comment]
Oh, 8.10.1 is already green!
